version: '3.7'

x-environment:
    &default-environment
    MYSQL_USER: vscode
    MYSQL_PASSWORD: notsecure
    MYSQL_DATABASE: tutorial
    MYSQL_ROOT_PASSWORD: rootpassword  # MySQL에서는 루트 비밀번호 설정이 필요함
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            <<: *default-environment
            PORT: 3000
        ports:
            - 3000:3000
        volumes:
            - ..:/workspace
        user: vscode
        command: sleep infinity
    db:
        image: "mysql:8"
        restart: unless-stopped
        environment: *default-environment
        ports:
            - 3306:3306  # MySQL 기본 포트는 3306
        volumes:
            - mysqldata:/var/lib/mysql  # MySQL의 데이터 디렉토리
            - ../mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
    mysqldata:
